/*.headers ON
.mode columns*/

PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS CARTAO;
CREATE TABLE CARTAO(
    idEvento INTEGER NOT NULL,
    cor TEXT NOT NULL,
    CONSTRAINT CARTAO_PK PRIMARY KEY (idEvento),
    CONSTRAINT CARTAO_FK FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
	CHECK (cor = 'Amarelo' or cor = 'Vermelho')
);

DROP TABLE IF EXISTS GOLO;
CREATE TABLE GOLO(
    idEvento INTEGER NOT NULL,
    idEquipa INTEGER NOT NULL,
    CONSTRAINT GOLO_PK PRIMARY KEY (idEvento),
    CONSTRAINT GOLO_FK1 FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
    CONSTRAINT GOLO_FK2 FOREIGN KEY (idEquipa) REFERENCES EQUIPA(idEquipa)
);

DROP TABLE IF EXISTS SUBSTITUICAO;
CREATE TABLE SUBSTITUICAO(
    idEvento INTEGER NOT NULL,
    idJogadorSubstituto INTEGER NOT NULL,
    CONSTRAINT SUBSTITUICAO_PK PRIMARY KEY (idEvento),
    CONSTRAINT SUBSTITUICAO_FK1 FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
    CONSTRAINT SUBSTITUICAO_FK1 FOREIGN KEY (idJogadorSubstituto) REFERENCES JOGADOR(idPessoa)
);

DROP TABLE IF EXISTS EVENTO;
CREATE TABLE EVENTO(
    idEvento INTEGER NOT NULL,
    idJogo INTEGER NOT NULL,
    idJogador INTEGER NOT NULL,
    minuto TEXT NOT NULL,
    CHECK (minuto > 0),
    CONSTRAINT EVENTO_PK PRIMARY KEY (idEvento),
    CONSTRAINT JOGO_FK FOREIGN KEY (idJogo) REFERENCES JOGO(idJogo),
    CONSTRAINT JOGADOR_FK FOREIGN KEY (idJogador) REFERENCES JOGADOR(idPessoa)
);

DROP TABLE IF EXISTS CONVOCATORIA;
CREATE TABLE CONVOCATORIA(
    idJogador INTEGER NOT NULL,
    idJogo INTEGER NOT NULL,
    CONSTRAINT CONVOCATORIA_PK1 PRIMARY KEY (idJogador, idJogo),
    CONSTRAINT CONVOCATORIA_FK1 FOREIGN KEY (idJogador) REFERENCES JOGADOR(idPessoa),
    CONSTRAINT CONVOCATORIA_FK2 FOREIGN KEY (idJogo) REFERENCES JOGO(idJogo)
);

DROP TABLE IF EXISTS JOGADOR;
CREATE TABLE JOGADOR(
    idPessoa INTEGER NOT NULL,
    idEquipa INTEGER NOT NULL,
	numCamisola INTEGER,
    CONSTRAINT JOGADOR_PK PRIMARY KEY (idPessoa),
    CONSTRAINT JOGADOR_FK1 FOREIGN KEY (idPessoa) REFERENCES PESSOA(idPessoa),
    CONSTRAINT JOGADOR_FK2 FOREIGN KEY (idEquipa) REFERENCES EQUIPA(idEquipa),
	CHECK (numCamisola >= 0 or numCamisola = NULL)
);

DROP TABLE IF EXISTS TREINADOR;
CREATE TABLE TREINADOR(
    idPessoa INTEGER NOT NULL,
	idEquipa INTEGER NOT NULL,
    CONSTRAINT TREINADOR_PK PRIMARY KEY (idPessoa),
    CONSTRAINT TREINADOR_FK FOREIGN KEY (idPessoa) REFERENCES PESSOA(idPessoa),
	CONSTRAINT TREINADOR_FK2 FOREIGN KEY (idEquipa) REFERENCES EQUIPA(idEquipa)
);

DROP TABLE IF EXISTS JOGO;
CREATE TABLE JOGO(
    idJogo INTEGER NOT NULL,
    data DATE NOT NULL,
    idJornada INTEGER NOT NULL,
    idEquipaFora INTEGER NOT NULL,
    idEquipaCasa INTEGER NOT NULL,
	nomeEstadio TEXT NOT NULL,
    CONSTRAINT JOGO_PK PRIMARY KEY (idJogo),
    CONSTRAINT JORNADA_FK FOREIGN KEY (idJornada) REFERENCES JORNADA(idJornada),
    CONSTRAINT EQUIPA_FORA_FK FOREIGN KEY (idEquipaFora) REFERENCES EQUIPA(idEquipa),
    CONSTRAINT EQUIPA_CASA_FK FOREIGN KEY (idEquipaCasa) REFERENCES EQUIPA(idEquipa),
	CONSTRAINT ESTADIO_FK FOREIGN KEY (nomeEstadio) REFERENCES ESTADIO(nomeEstadio)
);

DROP TABLE IF EXISTS EQUIPA;
CREATE TABLE EQUIPA(
    idEquipa INTEGER NOT NULL,
    nomeEquipa TEXT NOT NULL,
	nomeEstadio TEXT NOT NULL,
    CONSTRAINT EQUIPA_PK PRIMARY KEY (idEquipa),
	CONSTRAINT ESTADIO_FK FOREIGN KEY (nomeEstadio) REFERENCES ESTADIO(nomeEstadio)	
);

DROP TABLE IF EXISTS PESSOA;
CREATE TABLE PESSOA(
    idPessoa INTEGER NOT NULL,
    nome TEXT NOT NULL,
    idade INTEGER NOT NULL,
    nacionalidade TEXT NOT NULL,
    CONSTRAINT PESSOA_PK PRIMARY KEY (idPessoa),
    CHECK (idade >= 14)
);

DROP TABLE IF EXISTS ESTADIO;
CREATE TABLE ESTADIO(
	nomeEstadio TEXT NOT NULL,
	CONSTRAINT ESTADIO_PK PRIMARY KEY (nomeEstadio)
);

DROP TABLE IF EXISTS JORNADA;
CREATE TABLE JORNADA(
    idJornada TEXT NOT NULL,
    CONSTRAINT JORNADA_PK PRIMARY KEY (idJornada)
);
