/* Inserir 5 estrangeiros, da equipa 4 */

INSERT INTO "CONVOCATORIA" VALUES(160,1);
INSERT INTO "CONVOCATORIA" VALUES(158,1);
INSERT INTO "CONVOCATORIA" VALUES(164,1);
INSERT INTO "CONVOCATORIA" VALUES(169,1);
INSERT INTO "CONVOCATORIA" VALUES(179,1);


/*Ao inserir 5 estrangeiros da equipa 6, as linhas passam pq são de equipas diferentes */

INSERT INTO "CONVOCATORIA" VALUES(252,1);
INSERT INTO "CONVOCATORIA" VALUES(254,1);
INSERT INTO "CONVOCATORIA" VALUES(264,1);
INSERT INTO "CONVOCATORIA" VALUES(265,1);
INSERT INTO "CONVOCATORIA" VALUES(278,1);


/*Ao inserir jogadores não estrangeiros da equipa 4, as linhas tmb passam */

INSERT INTO "CONVOCATORIA" VALUES(150,1);
INSERT INTO "CONVOCATORIA" VALUES(151,1);
INSERT INTO "CONVOCATORIA" VALUES(152,1);
INSERT INTO "CONVOCATORIA" VALUES(153,1);
INSERT INTO "CONVOCATORIA" VALUES(154,1);


/* Mas ao inserir mais um estrangeiro da equipa 4, é levantado o erro */

INSERT INTO "CONVOCATORIA" VALUES(184,1);
