/* Inserção de 23 jogadores numa equipa, neste caso da equipa 4 */

INSERT INTO "CONVOCATORIA" VALUES(150,1);
INSERT INTO "CONVOCATORIA" VALUES(151,1);
INSERT INTO "CONVOCATORIA" VALUES(152,1);
INSERT INTO "CONVOCATORIA" VALUES(153,1);
INSERT INTO "CONVOCATORIA" VALUES(154,1);
INSERT INTO "CONVOCATORIA" VALUES(155,1);
INSERT INTO "CONVOCATORIA" VALUES(156,1);
INSERT INTO "CONVOCATORIA" VALUES(157,1);
INSERT INTO "CONVOCATORIA" VALUES(158,1);
INSERT INTO "CONVOCATORIA" VALUES(159,1);
INSERT INTO "CONVOCATORIA" VALUES(160,1);
INSERT INTO "CONVOCATORIA" VALUES(161,1);
INSERT INTO "CONVOCATORIA" VALUES(162,1);
INSERT INTO "CONVOCATORIA" VALUES(163,1);
INSERT INTO "CONVOCATORIA" VALUES(164,1);
INSERT INTO "CONVOCATORIA" VALUES(165,1);
INSERT INTO "CONVOCATORIA" VALUES(166,1);
INSERT INTO "CONVOCATORIA" VALUES(167,1);
INSERT INTO "CONVOCATORIA" VALUES(168,1);
INSERT INTO "CONVOCATORIA" VALUES(169,1);
INSERT INTO "CONVOCATORIA" VALUES(170,1);
INSERT INTO "CONVOCATORIA" VALUES(171,1);
INSERT INTO "CONVOCATORIA" VALUES(172,1);


/* Estas linhas não vão falhar porque são de 
uma equipa diferente da anterior, da equipa 6 */

INSERT INTO "CONVOCATORIA" VALUES(248,1);
INSERT INTO "CONVOCATORIA" VALUES(249,1);
INSERT INTO "CONVOCATORIA" VALUES(250,1);
INSERT INTO "CONVOCATORIA" VALUES(251,1);
INSERT INTO "CONVOCATORIA" VALUES(252,1);

/* Sendo esta da equipa 4, esta não vai passar */

INSERT INTO "CONVOCATORIA" VALUES(173,1);


